language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: required

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  # Deactivate xdebug and both error and warning messages
  - echo "error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING" > php.ini
  - phpenv config-rm xdebug.ini
  - phpenv config-add php.ini

  # Install PHP dependencies
  - composer install

  # Download PhantomJS 2 for Ubuntu Precise Pangolin.
  # Because there is only PhantomJS 1.9.* pre-installed.
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xf phantomjs-2.0.0-ubuntu-12.04.tar.bz2

  # CodeCeption has to use our own PhantomJS binary.
  - sed -i 's/phantomjs/.\/phantomjs/g' codeception.yml

script:
  - ./vendor/bin/codecept run